## Question 1: Creating a NumPy Array  
Write a Python code snippet to create a NumPy array of 10 zeros.

### Example:
- **Output:**  
  `array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])`


In [5]:
import numpy as np

# Create a NumPy array of 10 zeros
array_of_zeros = np.zeros(10)

# Print the array
print(array_of_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]




## Question 2: Creating a Range of Numbers  
Write a Python code snippet to create a NumPy array with numbers from 10 to 20 (inclusive) with a step of 2.

### Example:
- **Output:**  
  `array([10, 12, 14, 16, 18, 20])`

In [7]:
# Write your code here
import numpy as np

# Create a NumPy array with numbers from 10 to 20 (inclusive) with a step of 2
array = np.arange(10, 21, 2)

# Print the array
print(array)


[10 12 14 16 18 20]


## Question 3: Reshaping an Array  
Write a Python code snippet to reshape a NumPy array with 12 elements into a 3x4 matrix.

### Example:
- **Input:**  
  `array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])`
  
- **Output:**  
  `array([[ 1,  2,  3,  4],  
         [ 5,  6,  7,  8],  
         [ 9, 10, 11, 12]])`

In [9]:
# Write your code here
import numpy as np

# Create a NumPy array with 12 elements
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the array into a 3x4 matrix
reshaped_array = array.reshape(3, 4)

# Print the reshaped array
print(reshaped_array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Question 4: Array Indexing  
Write a Python code snippet to retrieve the element at the 2nd row and 3rd column from a 3x4 matrix.

### Example:
- **Input:**  
  `array([[1, 2, 3, 4],  
         [5, 6, 7, 8],  
         [9, 10, 11, 12]])`
  
- **Output:**  
  `11`

In [11]:
# Write your code here
import numpy as np

# Create a NumPy 3x4 matrix
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Retrieve the element at the 2nd row and 3rd column (index 1, 2)
element = array[1, 2]

# Print the element
print(element)


7



## Question 5: Array Operations  
Write a Python code snippet to add 5 to every element of the following NumPy array.

### Example:
- **Input:**  
  `array([1, 2, 3, 4, 5])`
  
- **Output:**  
  `array([6, 7, 8, 9, 10])`

In [13]:
# Write your code here
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Add 5 to every element of the array
result = array + 5

# Print the result
print(result)


[ 6  7  8  9 10]


## Question 6: Array Transposition  
Write a Python code snippet to transpose a 2x3 NumPy array.

### Example:
- **Input:**  
  `array([[1, 2, 3],  
         [4, 5, 6]])`
  
- **Output:**  
  `array([[1, 4],  
         [2, 5],  
         [3, 6]])`

In [15]:
# Write your code here
import numpy as np

# Create a 2x3 NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Transpose the array
transposed_array = array.T

# Print the transposed array
print(transposed_array)



[[1 4]
 [2 5]
 [3 6]]



## Question 7: Array Arithmetic  
Write a Python code snippet to multiply two NumPy arrays element-wise.

### Example:
- **Input:**  
  `array([1, 2, 3])`,  
  `array([4, 5, 6])`
  
- **Output:**  
  `array([4, 10, 18])`

In [17]:
# Write your code here
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Multiply the arrays element-wise
result = array1 * array2

# Print the result
print(result)



[ 4 10 18]



## Question 9: Statistical Functions  
Write a Python code snippet to compute the mean of a NumPy array.

### Example:
- **Input:**  
  `array([10, 20, 30, 40, 50])`
  
- **Output:**  
  `30.0`

In [1]:
# Write your code here
import numpy as np
array=[10,20,30,40,50]
mean=np.mean(array)
print(mean)

30.0


## Question 8: Boolean Indexing  
Write a Python code snippet to create a new NumPy array by selecting elements greater than 5 from the following array.

### Example:
- **Input:**  
  `array([1, 2, 3, 6, 7, 8])`
  
- **Output:**  
  `array([6, 7, 8])`

In [19]:
# Write your code here
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 6, 7, 8])

# Select elements greater than 5
result = array[array > 5]

# Print the result
print(result)


[6 7 8]


## Question 10: Stacking Arrays  
Write a Python code snippet to stack two NumPy arrays vertically.

### Example:
- **Input:**  
  `array([1, 2, 3])`,  
  `array([4, 5, 6])`
  
- **Output:**  
  `array([[1, 2, 3],  
         [4, 5, 6]])`


In [21]:
# Write your code here
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays vertically
stacked_array = np.vstack((array1, array2))

# Print the stacked array
print(stacked_array)



[[1 2 3]
 [4 5 6]]


## Question 11: Creating an Identity Matrix  
Write a Python code snippet to create a 3x3 identity matrix using NumPy.

### Example:
- **Output:**  
  `array([[1., 0., 0.],  
         [0., 1., 0.],  
         [0., 0., 1.]])`


In [23]:
# Write your code here
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Print the identity matrix
print(identity_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Question 12: Array Dot Product  
Write a Python code snippet to compute the dot product of two NumPy arrays.

### Example:
- **Input:**  
  `array([1, 2])`,  
  `array([3, 4])`
  
- **Output:**  
  `11`

In [25]:
# Write your code here
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2])
array2 = np.array([3, 4])

# Compute the dot product
dot_product = np.dot(array1, array2)

# Print the result
print(dot_product)


11


## Question 13: Creating a Random Array  
Write a Python code snippet to create a NumPy array of 5 random numbers between 0 and 1.



In [27]:
# Write your code here
import numpy as np

# Create an array of 5 random numbers between 0 and 1
random_array = np.random.rand(5)

# Print the array
print(random_array)



[0.24808229 0.32415611 0.11221036 0.08409719 0.30896647]


## Question 14: Array Sorting  
Write a Python code snippet to sort a NumPy array in ascending order.

### Example:
- **Input:**  
  `array([3, 1, 4, 1, 5, 9, 2])`
  
- **Output:**  
  `array([1, 1, 2, 3, 4, 5, 9])`

In [29]:
# Write your code here
import numpy as np

# Create a NumPy array
array = np.array([3, 1, 4, 1, 5, 9, 2])

# Sort the array in ascending order
sorted_array = np.sort(array)

# Print the sorted array
print(sorted_array)



[1 1 2 3 4 5 9]


## Question 15: Array Broadcasting  
Write a Python code snippet to add a 1D array to a 2D array using broadcasting.

### Example:
- **Input:**  
  `array([[1, 2],  
         [3, 4]])`,  
  `array([10, 20])`
  
- **Output:**  
  `array([[11, 22],  
         [13, 24]])`


In [31]:
# Write your code here
import numpy as np

# Create a 2D NumPy array
array_2d = np.array([[1, 2],
                     [3, 4]])

# Create a 1D NumPy array
array_1d = np.array([10, 20])

# Add the 1D array to the 2D array using broadcasting
result = array_2d + array_1d

# Print the result
print(result)


[[11 22]
 [13 24]]



## Question 16: Reshaping with `-1`  
Write a Python code snippet to reshape a NumPy array with 9 elements into a 3x3 matrix using `-1` for automatic dimension calculation.

### Example:
- **Input:**  
  `array([1, 2, 3, 4, 5, 6, 7, 8, 9])`
  
- **Output:**  
  `array([[1, 2, 3],  
         [4, 5, 6],  
         [7, 8, 9]])`

In [33]:
# Write your code here
import numpy as np

# Create a NumPy array with 9 elements
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape the array into a 3x3 matrix using -1 for automatic dimension calculation
reshaped_array = array.reshape(3, -1)

# Print the reshaped array
print(reshaped_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Question 17: Element-wise Square  
Write a Python code snippet to square each element in a NumPy array.

### Example:
- **Input:**  
  `array([1, 2, 3, 4])`
  
- **Output:**  
  `array([1, 4, 9, 16])`


In [17]:
# Write your code here
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4])

# Square each element using np.square
squared_array = np.square(array)


# Print the result
print(squared_array)



## Question 18: Counting Elements  
Write a Python code snippet to count the occurrences of a particular element (e.g., 3) in a NumPy array.

### Example:
- **Input:**  
  `array([1, 2, 3, 3, 4, 3])`
  
- **Output:**  
  `3`

In [35]:
# Write your code here
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 3, 4, 3])

# Count the occurrences of the element 3
count = np.sum(array == 3)

# Print the result
print(count)


3
